version: '3'
services:
  # Routeurs
  routeur_1:
    image: mongo
    container_name: routeur_1
    ports:
      - "27017:27017"
    command: mongos --configdb routeur_1/localhost:27017

  routeur_2:
    image: mongo
    container_name: routeur_2
    ports:
      - "27018:27017"
    command: mongos --configdb routeur_2/localhost:27017

  routeur_3:
    image: mongo
    container_name: routeur_3
    ports:
      - "27019:27017"
    command: mongos --configdb routeur_3/localhost:27017

  # Serveur Principal A
  principal_a:
    image: mongo
    container_name: principal_a
    ports:
      - "27020:27017"
    command: mongod --replSet rs0

  # Serveur Principal B
  principal_b:
    image: mongo
    container_name: principal_b
    ports:
      - "27021:27017"
    command: mongod --replSet rs1
